### ISSUE TITLE
Vite JS build error (rollup): Illegal reassignment to import '$'

### ISSUE THREAD

**Issue by diggy** [DataTables/DataTablesSrc#226]
Error with the latest [commit](https://github.com/DataTables/Dist-DataTables/commit/44a8a3ce0e578f2731de6235348ea0b0da54c7ae) in the `Dist-DataTables` repo ("[Add support for mjs files (ES Modules)](https://github.com/DataTables/Dist-DataTables/commit/44a8a3ce0e578f2731de6235348ea0b0da54c7ae)").

ES6 import syntax as per the [readme](https://github.com/DataTables/Dist-DataTables#npm):

```
import 'datatables.net'
```

Terminal output:

```
$ npm run build

> build
> vite build

vite v3.1.8 building for production...

✓ 79 modules transformed.

Illegal reassignment to import '$'

file: /path/to/node_modules/datatables.net/js/jquery.dataTables.mjs:15539:2

15537: DataTable.use = function (module, type) {
15538:   if (type === 'lib' || module.fn) {
15539:     $ = module;
           ^
15540:   }
15541:   else if (type == 'win' || module.document) {

error during build:

Error: Illegal reassignment to import '$'
    at error (file:///path/to/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///path/to/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Identifier.disallowImportReassignment (file:///path/to/node_modules/rollup/dist/es/shared/rollup.js:7583:29)
    at Identifier.deoptimizePath (file:///path/to/node_modules/rollup/dist/es/shared/rollup.js:7477:18)
    at AssignmentExpression.applyDeoptimizations (file:///path/to/node_modules/rollup/dist/es/shared/rollup.js:8184:19)
    at AssignmentExpression.hasEffects (file:///path/to/node_modules/rollup/dist/es/shared/rollup.js:8110:18)
    at ExpressionStatement.hasEffects (file:///path/to/node_modules/rollup/dist/es/shared/rollup.js:5292:28)
    at BlockStatement.hasEffects (file:///path/to/node_modules/rollup/dist/es/shared/rollup.js:7823:22)
    at BlockStatement.shouldBeIncluded (file:///path/to/node_modules/rollup/dist/es/shared/rollup.js:5380:62)
    at IfStatement.includeUnknownTest (file:///path/to/node_modules/rollup/dist/es/shared/rollup.js:9973:29)
```

**Comment by diggy** [comment]
output with `npm run dev`:

```
✘ [ERROR] Cannot assign to import "$"

    node_modules/datatables.net/js/jquery.dataTables.mjs:15539:2:
      15539 │     $ = module;
            ╵     ^

  Imports are immutable in JavaScript. To modify the value of this import, you must export a setter
  function in the imported file (e.g. "set$") and then import and call that function here instead.

/path/to/node_modules/vite/node_modules/esbuild/lib/main.js:1566
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/datatables.net/js/jquery.dataTables.mjs:15539:2: ERROR: Cannot assign to import "$"
    at failureErrorWithLog (/path/to/node_modules/vite/node_modules/esbuild/lib/main.js:1566:15)
    at /path/to/node_modules/vite/node_modules/esbuild/lib/main.js:1024:28
    at runOnEndCallbacks (/path/to/node_modules/vite/node_modules/esbuild/lib/main.js:1438:61)
    at buildResponseToResult (/path/to/node_modules/vite/node_modules/esbuild/lib/main.js:1022:7)
    at /path/to/node_modules/vite/node_modules/esbuild/lib/main.js:1134:14
    at responseCallbacks.<computed> (/path/to/node_modules/vite/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/path/to/node_modules/vite/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/path/to/node_modules/vite/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 2,
        file: 'node_modules/datatables.net/js/jquery.dataTables.mjs',
        length: 1,
        line: 15539,
        lineText: '\t\t$ = module;',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'Imports are immutable in JavaScript. To modify the value of this import, you must export a setter function in the imported file (e.g. "set$") and then import and call that function here instead.'
        }
      ],
      pluginName: '',
      text: 'Cannot assign to import "$"'
    }
  ],
  warnings: []
}

Node.js v18.11.0
```

**Comment by AllanJard** [comment]
Thanks for testing the latest build! [Fix for that now committed](https://github.com/DataTables/DataTablesSrc/commit/804120ca48084274aafb02542b6d4202ff6df3cc).
